import { DataTypes } from 'sequelize'
import sequelize from './db'

const Staff = sequelize.define('Staff', {
  // Model attributes are defined here
  staffId:              { type: DataTypes.INTEGER, field: 'staff_id', allowNull: false, },
  photo:                { type: DataTypes.TEXT, },
  fullName:             { type: DataTypes.STRING, field: 'full_name', allowNull: false, },
  furigana:             { type: DataTypes.STRING, },
  maidenName:           { type: DataTypes.STRING, field: 'maiden_name', },
  sex:                  { type: DataTypes.STRING, },
  bloodType:            { type: DataTypes.STRING, field: 'blood_type', },
  birthDate:            { type: DataTypes.DATEONLY, field: 'birth_date', },
  joinDate:             { type: DataTypes.DATEONLY, field: 'join_date', },
  employedCategory:     { type: DataTypes.STRING, field: 'employed_category', },
  location:             { type: DataTypes.STRING, },
  projectName:          { type: DataTypes.STRING, field: 'project_name', },
  startDate:            { type: DataTypes.DATEONLY, field: 'start_date', },
  department:           { type: DataTypes.STRING, },
  position:             { type: DataTypes.STRING, },
  staffCategory:        { type: DataTypes.STRING, field: 'staff_category', },
  isLinkage:            { type: DataTypes.BOOLEAN, field: 'is_linkage', },
  staffRank:            { type: DataTypes.STRING, field: 'staff_rank', },
  postalCode:           { type: DataTypes.STRING, field: 'postal_code', },
  address1:             { type: DataTypes.STRING, },
  address2:             { type: DataTypes.STRING, },
  address3:             { type: DataTypes.STRING, },
  phoneNumber:          { type: DataTypes.STRING, field: 'phone_number', },
  mobileNumber:         { type: DataTypes.STRING, field: 'mobile_number', },
  isMailing:            { type: DataTypes.BOOLEAN, field: 'is_mailing', },
  mailingPostalCode:    { type: DataTypes.STRING, field: 'mailing_postal_code', },
  mailingAddress1:      { type: DataTypes.STRING, field: 'mailing_address1', },
  mailingAddress2:      { type: DataTypes.STRING, field: 'mailing_address2', },
  mailingAddress3:      { type: DataTypes.STRING, field: 'mailing_address3', },
  mailingPhoneNumber:   { type: DataTypes.STRING, field: 'mailing_phone_number', },
  residencePostalCode:    { type: DataTypes.STRING, field: 'residence_postal_code', },
  residenceAddress1:      { type: DataTypes.STRING, field: 'residence_address1', },
  residenceAddress2:      { type: DataTypes.STRING, field: 'residence_address2', },
  residenceAddress3:      { type: DataTypes.STRING, field: 'residence_address3', },
  residencePhoneNumber:   { type: DataTypes.STRING, field: 'residence_phone_number', },
  line1:                { type: DataTypes.STRING, },
  station1:             { type: DataTypes.STRING, },
  line2:                { type: DataTypes.STRING, },
  station2:             { type: DataTypes.STRING, },
  line3:                { type: DataTypes.STRING, },
  station3:             { type: DataTypes.STRING, },
  emergencyFullName:    { type: DataTypes.STRING, field: 'emergency_full_name', },
  emergencyFurigana:    { type: DataTypes.STRING, field: 'emergency_furigana', },
  emergencyRelation:    { type: DataTypes.STRING, field: 'emergency_relation', },
  emergencyIsLiveWith:  { type: DataTypes.BOOLEAN, field: 'emergency_is_live_with', },
  emergencyPostalCode:  { type: DataTypes.STRING, field: 'emergency_postal_code', },
  emergencyAddress1:    { type: DataTypes.STRING, field: 'emergency_address1', },
  emergencyAddress2:    { type: DataTypes.STRING, field: 'emergency_address2', },
  emergencyAddress3:    { type: DataTypes.STRING, field: 'emergency_address3', },
  emergencyPhoneNumber: { type: DataTypes.STRING, field: 'emergency_phone_number', },
  remarks:              { type: DataTypes.STRING, },
  handicappedCategory:  { type: DataTypes.STRING, field: 'handicapped_category', },
  leaveDate:            { type: DataTypes.DATEONLY, field: 'leave_date', },
  leaveReason:          { type: DataTypes.STRING, field: 'leave_reason', },
  notes:                { type: DataTypes.TEXT, },
  createdAt:            { type: DataTypes.DATE, field: 'created_at', },
  updatedAt:            { type: DataTypes.DATE, field: 'updated_at', },
}, {
  freezeTableName: true
});

export default Staff
